import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';

const { NEXT_PUBLIC_VERCEL_ENV = 'development' } = process.env;
export const metadata = {
  title: 'lucky',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string; program?: boolean }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Lucky', path: '/lucky', program: true },
  { label: 'TinyAdventure', path: '/tiny-adventure', program: true },
  { label: 'Dealer', path: '/dealer', program: true },
];

if (NEXT_PUBLIC_VERCEL_ENV !== 'production')
  links.push({ label: 'Clusters', path: '/clusters' });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links} env={NEXT_PUBLIC_VERCEL_ENV}>
                {children}
              </UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
